version: "3.9"
services:
    applogina:
        build: .
        ports:
            - "8443:443"
            - "8080:80"
        networks:
            - mired
        depends_on:
            - ricksql
            - melsql 
        environment: # Agregar aquí la variable de entorno ASPNETCORE_ENVIRONMENT
            - ASPNETCORE_ENVIRONMENT=Development # O el valor que desees (Development, Production, etc.)
        volumes:
            - /app   
    ricksql:
        image: rickuub/youtube:latest
        ports: 
            - "3308:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=passwd
        networks:
            - mired
    melsql:
        image: melvincevallos/noticias:latest
        ports: 
            - "3307:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=passwd
        networks:
            - mired
networks:
  mired: